### ISSUE TITLE
multi-touch event structs have incorrect information

### ISSUE THREAD

**Issue by rkomar** [pocketbook-free/SDK_481#1]
I am running an application on my Inkpad with firmware sw_20141023_840_W_5.4_98_bookstore_rr_s2pb_syncV2_us_user.zip.  When I look at the multi-touch data returned by GetTouchInfo(), the (x,y) coordinates of the second member in the array are incorrect.  They are usually (0,0) in the struct.  However, it looks like the actual coordinates are stored in rsv_1 and rsv_2.  The same code works well under sw_20141212_840_W_br_4.4_1277_default_daily_user-1.zip when I build with the old SDK.  I don't know if this is a bug in the firmware, or if the iv_mtinfo struct has changed in the firmware, but not in the SDK.

**Comment by pocketbook-free** [comment]
Hello,
the problem is that inkview.h version is old, it was updated it 5.4 firmware.
We will share it nearest days here

**Comment by rkomar** [comment]
Okay, thanks!  It shouldn't be too hard to work around this change by checking the firmware version number in the application.
