### ISSUE TITLE
Outdated gcc 4.8.1 is starting to cause issues

### ISSUE THREAD

**Issue by Frenzie** [pocketbook-free/SDK_481#3]
For example, HarfBuzz 2.1.1 doesn't like it.

Is there anything special about the compiler itself?

**Comment by pocketbook-free** [comment]
If you need to port harfbuzz to old device, you should choose some older one, if you need it for present-days devices and firmwares, please wait a little, we will publicate an updated SDK nearest days on https://github.com/pocketbook/
